// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOOeH6URnPc7_fxhR3WZD3_lRpUu727s',
    appId: '1:183792762346:web:de8fe6e620ec67813bc693',
    messagingSenderId: '183792762346',
    projectId: 'covoiturage-1dc44',
    authDomain: 'covoiturage-1dc44.firebaseapp.com',
    storageBucket: 'covoiturage-1dc44.appspot.com',
    measurementId: 'G-1TJBMSJ0ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmbWnwA-VElYf8H-q8lDDhGKGbFKTHRUE',
    appId: '1:183792762346:android:2e39d6974f05d97b3bc693',
    messagingSenderId: '183792762346',
    projectId: 'covoiturage-1dc44',
    storageBucket: 'covoiturage-1dc44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClMIrfJXxQrC08i-qP0YNlODhOufCBe4s',
    appId: '1:183792762346:ios:bd58f45879814da73bc693',
    messagingSenderId: '183792762346',
    projectId: 'covoiturage-1dc44',
    storageBucket: 'covoiturage-1dc44.appspot.com',
    iosBundleId: 'com.example.covoiturage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClMIrfJXxQrC08i-qP0YNlODhOufCBe4s',
    appId: '1:183792762346:ios:dcd55939caf7f2423bc693',
    messagingSenderId: '183792762346',
    projectId: 'covoiturage-1dc44',
    storageBucket: 'covoiturage-1dc44.appspot.com',
    iosBundleId: 'com.example.covoiturage.RunnerTests',
  );
}
