// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOG2ug4eu350FHhtJsbTH8_7vld_dGeO0',
    appId: '1:411384642220:web:0eb4e3b202bf330b3b7d09',
    messagingSenderId: '411384642220',
    projectId: 'authapp-60368',
    authDomain: 'authapp-60368.firebaseapp.com',
    storageBucket: 'authapp-60368.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcK014C3Ws2DQINAQFwR7B63TXiObUdpQ',
    appId: '1:411384642220:android:aebc2cf711cd9f343b7d09',
    messagingSenderId: '411384642220',
    projectId: 'authapp-60368',
    storageBucket: 'authapp-60368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCznrhrS4OpoVEbSvA1jIXgr6Ccs5ANuFM',
    appId: '1:411384642220:ios:829c19c8e673fb3b3b7d09',
    messagingSenderId: '411384642220',
    projectId: 'authapp-60368',
    storageBucket: 'authapp-60368.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCznrhrS4OpoVEbSvA1jIXgr6Ccs5ANuFM',
    appId: '1:411384642220:ios:829c19c8e673fb3b3b7d09',
    messagingSenderId: '411384642220',
    projectId: 'authapp-60368',
    storageBucket: 'authapp-60368.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
